"""
coco_to_yolo.py — 把 screen COCO 標注轉成 YOLO 格式，用來訓練多 class 球員偵測器。

Class mapping:
  0 = ball_handler   （持球者，最重要）
  1 = screener       （掩護者）
  2 = defender       （掩護的防守者）
  3 = others         （其他進攻球員）

(略過 'screen', 'target', 'player' — 'screen'/'target' 是動作 bbox 不是人，'player' 標注數太少)

輸出結構:
  yolo_screen_dataset/
    images/train/<image>.jpg
    images/val/<image>.jpg
    labels/train/<image>.txt
    labels/val/<image>.txt
    data.yaml

Usage:
  python nba_data_pipeline/coco_to_yolo.py
"""

import json
import random
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
COCO_PATH    = PROJECT_ROOT / 'screen_data' / 'screen_v2.coco' / 'train' / '_annotations.coco.json'
IMG_DIR      = PROJECT_ROOT / 'screen_data' / 'screen_v2.coco' / 'train'
OUT_DIR      = PROJECT_ROOT / 'yolo_screen_dataset'

VAL_RATIO = 0.1
SEED      = 42

# 要保留的 COCO category name → YOLO class index
CLASS_MAP = {
    'ball_handler': 0,
    'screener':     1,
    'defender':     2,
    'others':       3,
}
CLASS_NAMES = ['ball_handler', 'screener', 'defender', 'others']


def main():
    print(f"Loading {COCO_PATH}")
    with open(COCO_PATH, encoding='utf-8') as f:
        coco = json.load(f)

    cat_map = {c['id']: c['name'] for c in coco['categories']}
    img_meta = {img['id']: img for img in coco['images']}

    # image_id → list[(yolo_class, x_center, y_center, w, h)] (normalized)
    img_labels = {iid: [] for iid in img_meta}

    skipped_cat = 0
    for ann in coco['annotations']:
        cat_name = cat_map[ann['category_id']]
        if cat_name not in CLASS_MAP:
            skipped_cat += 1
            continue
        yolo_class = CLASS_MAP[cat_name]
        x, y, w, h = [float(v) for v in ann['bbox']]
        img = img_meta[ann['image_id']]
        W, H = float(img['width']), float(img['height'])
        xc = (x + w / 2) / W
        yc = (y + h / 2) / H
        bw = w / W
        bh = h / H
        img_labels[ann['image_id']].append((yolo_class, xc, yc, bw, bh))

    # 過濾沒有任何 player 標注的圖
    img_ids_with_labels = [iid for iid, labels in img_labels.items() if labels]
    print(f"  Skipped annotations (other categories): {skipped_cat}")
    print(f"  Images with player labels: {len(img_ids_with_labels)}/{len(img_meta)}")

    # Train / val split
    random.seed(SEED)
    random.shuffle(img_ids_with_labels)
    val_size = int(len(img_ids_with_labels) * VAL_RATIO)
    val_ids = set(img_ids_with_labels[:val_size])
    train_ids = set(img_ids_with_labels[val_size:])

    print(f"  Train: {len(train_ids)}  Val: {len(val_ids)}")

    # 建資料夾
    for split in ('train', 'val'):
        (OUT_DIR / 'images' / split).mkdir(parents=True, exist_ok=True)
        (OUT_DIR / 'labels' / split).mkdir(parents=True, exist_ok=True)

    # 複製圖片 + 寫 label
    n_copied = 0
    n_missing = 0
    for iid in img_ids_with_labels:
        img = img_meta[iid]
        split = 'val' if iid in val_ids else 'train'

        src_img = IMG_DIR / img['file_name']
        if not src_img.exists():
            n_missing += 1
            continue
        dst_img = OUT_DIR / 'images' / split / src_img.name
        if not dst_img.exists():
            shutil.copy2(src_img, dst_img)
            n_copied += 1

        # 寫 YOLO label
        label_path = OUT_DIR / 'labels' / split / f"{src_img.stem}.txt"
        with open(label_path, 'w') as f:
            for cls, xc, yc, bw, bh in img_labels[iid]:
                f.write(f"{cls} {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}\n")

    print(f"  Copied {n_copied} images, missing {n_missing}")

    # 寫 data.yaml
    yaml_path = OUT_DIR / 'data.yaml'
    yaml_content = (
        f"# Generated by coco_to_yolo.py\n"
        f"# path 改成執行時 dataset 所在絕對路徑（YOLO 在不同機器跑時要改）\n"
        f"path: .\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"\n"
        f"nc: {len(CLASS_NAMES)}\n"
        f"names:\n"
    )
    for i, name in enumerate(CLASS_NAMES):
        yaml_content += f"  {i}: {name}\n"

    with open(yaml_path, 'w') as f:
        f.write(yaml_content)

    print(f"\nDone. Dataset → {OUT_DIR}")
    print(f"data.yaml:")
    print(yaml_content)
    print(f"Next step (in venv with ultralytics):")
    print(f"  yolo detect train data={yaml_path.resolve()} model=models/player_detector.pt epochs=50 imgsz=640")


if __name__ == '__main__':
    main()
